# Generated by Django 5.1.1 on 2024-10-19 14:13

import news.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.utils.upload_image_news, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'New Arabic',
                'verbose_name_plural': 'News Arabic',
            },
        ),
        migrations.CreateModel(
            name='NewsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.utils.upload_image_news, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'New English',
                'verbose_name_plural': 'News English',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
