from django.urls import path, include
from . import views

app_name = "dashboard"

urlpatterns = [
    # =============== Slider ===============
    path("en/sliders/", views.SlidersEnglishListView.as_view(),
         name="en_slider_dashboard_list"),
    path("en/sliders/create/", views.SlidersEnglishCreateView.as_view(),
         name="en_slider_dashboard_create"),
    path("en/sliders/<int:id>/", views.SlidersEnglishDetailView.as_view(),
         name="en_slider_dashboard_detail"),
    path("en/sliders/<int:id>/update/", views.SlidersEnglishUpdateView.as_view(),
         name="en_slider_dashboard_update"),
    path("en/sliders/<int:id>/delete/", views.SlidersEnglishDeleteView.as_view(),
         name="en_slider_dashboard_delete"),

    path("ar/sliders/", views.SlidersArabicListView.as_view(),
         name="ar_slider_dashboard_list"),
    path("ar/sliders/create/", views.SlidersArabicCreateView.as_view(),
         name="ar_slider_dashboard_create"),
    path("ar/sliders/<int:id>/", views.SlidersArabicDetailView.as_view(),
         name="ar_slider_dashboard_detail"),
    path("ar/sliders/<int:id>/update/", views.SlidersArabicUpdateView.as_view(),
         name="ar_slider_dashboard_update"),
    path("ar/sliders/<int:id>/delete/", views.SlidersArabicDeleteView.as_view(),
         name="ar_slider_dashboard_delete"),

    # =============== AboutUs ===============
    path("en/about_us/", views.AboutUsEnglishListView.as_view(),
         name="en_about_us_dashboard_list"),
    path("en/about_us/create/", views.AboutUsEnglishCreateView.as_view(),
         name="en_about_us_dashboard_create"),
    path("en/about_us/<int:id>/", views.AboutUsEnglishDetailView.as_view(),
         name="en_about_us_dashboard_detail"),
    path("en/about_us/<int:id>/update/", views.AboutUsEnglishUpdateView.as_view(),
         name="en_about_us_dashboard_update"),
    path("en/about_us/<int:id>/delete/", views.AboutUsEnglishDeleteView.as_view(),
         name="en_about_us_dashboard_delete"),

    path("ar/about_us/", views.AboutUsArabicListView.as_view(),
         name="ar_about_us_dashboard_list"),
    path("ar/about_us/create/", views.AboutUsArabicCreateView.as_view(),
         name="ar_about_us_dashboard_create"),
    path("ar/about_us/<int:id>/", views.AboutUsArabicDetailView.as_view(),
         name="ar_about_us_dashboard_detail"),
    path("ar/about_us/<int:id>/update/", views.AboutUsArabicUpdateView.as_view(),
         name="ar_about_us_dashboard_update"),
    path("ar/about_us/<int:id>/delete/", views.AboutUsArabicDeleteView.as_view(),
         name="ar_about_us_dashboard_delete"),

    # =============== ChooseUs ===============
    path("en/choose_us/", views.ChooseUsEnglishListView.as_view(),
         name="en_choose_us_dashboard_list"),
    path("en/choose_us/create/", views.ChooseUsEnglishCreateView.as_view(),
         name="en_choose_us_dashboard_create"),
    path("en/choose_us/<int:id>/", views.ChooseUsEnglishDetailView.as_view(),
         name="en_choose_us_dashboard_detail"),
    path("en/choose_us/<int:id>/update/", views.ChooseUsEnglishUpdateView.as_view(),
         name="en_choose_us_dashboard_update"),
    path("en/choose_us/<int:id>/delete/", views.ChooseUsEnglishDeleteView.as_view(),
         name="en_choose_us_dashboard_delete"),

    path("ar/choose_us/", views.ChooseUsArabicListView.as_view(),
         name="ar_choose_us_dashboard_list"),
    path("ar/choose_us/create/", views.ChooseUsArabicCreateView.as_view(),
         name="ar_choose_us_dashboard_create"),
    path("ar/choose_us/<int:id>/", views.ChooseUsArabicDetailView.as_view(),
         name="ar_choose_us_dashboard_detail"),
    path("ar/choose_us/<int:id>/update/", views.ChooseUsArabicUpdateView.as_view(),
         name="ar_choose_us_dashboard_update"),
    path("ar/choose_us/<int:id>/delete/", views.ChooseUsArabicDeleteView.as_view(),
         name="ar_choose_us_dashboard_delete"),


    # =============== Service ===============
    path("en/service/", views.ServiceEnglishListView.as_view(),
         name="en_service_dashboard_list"),
    path("en/service/create/", views.ServiceEnglishCreateView.as_view(),
         name="en_service_dashboard_create"),
    path("en/service/<int:id>/", views.ServiceEnglishDetailView.as_view(),
         name="en_service_dashboard_detail"),
    path("en/service/<int:id>/update/", views.ServiceEnglishUpdateView.as_view(),
         name="en_service_dashboard_update"),
    path("en/service/<int:id>/delete/", views.ServiceEnglishDeleteView.as_view(),
         name="en_service_dashboard_delete"),

    path("ar/service/", views.ServiceArabicListView.as_view(),
         name="ar_service_dashboard_list"),
    path("ar/service/create/", views.ServiceArabicCreateView.as_view(),
         name="ar_service_dashboard_create"),
    path("ar/service/<int:id>/", views.ServiceArabicDetailView.as_view(),
         name="ar_service_dashboard_detail"),
    path("ar/service/<int:id>/update/", views.ServiceArabicUpdateView.as_view(),
         name="ar_service_dashboard_update"),
    path("ar/service/<int:id>/delete/", views.ServiceArabicDeleteView.as_view(),
         name="ar_service_dashboard_delete"),
    # =============== Comments ===============
    path("en/comments/", views.CommentsEnglishListView.as_view(),
         name="en_comments_dashboard_list"),
    path("en/comments/create/", views.CommentsEnglishCreateView.as_view(),
         name="en_comments_dashboard_create"),
    path("en/comments/<int:id>/", views.CommentsEnglishDetailView.as_view(),
         name="en_comments_dashboard_detail"),
    path("en/comments/<int:id>/update/", views.CommentsEnglishUpdateView.as_view(),
         name="en_comments_dashboard_update"),
    path("en/comments/<int:id>/delete/", views.CommentsEnglishDeleteView.as_view(),
         name="en_comments_dashboard_delete"),

    path("ar/comments/", views.CommentsArabicListView.as_view(),
         name="ar_comments_dashboard_list"),
    path("ar/comments/create/", views.CommentsArabicCreateView.as_view(),
         name="ar_comments_dashboard_create"),
    path("ar/comments/<int:id>/", views.CommentsArabicDetailView.as_view(),
         name="ar_comments_dashboard_detail"),
    path("ar/comments/<int:id>/update/", views.CommentsArabicUpdateView.as_view(),
         name="ar_comments_dashboard_update"),
    path("ar/comments/<int:id>/delete/", views.CommentsArabicDeleteView.as_view(),
         name="ar_comments_dashboard_delete"),

    # =============== Suggestions ===============
    path("en/suggestions/", views.SuggestionsEnglishListView.as_view(),
         name="en_suggestions_dashboard_list"),
    path("en/suggestions/create/", views.SuggestionsEnglishCreateView.as_view(),
         name="en_suggestions_dashboard_create"),
    path("en/suggestions/<int:id>/", views.SuggestionsEnglishDetailView.as_view(),
         name="en_suggestions_dashboard_detail"),
    path("en/suggestions/<int:id>/update/", views.SuggestionsEnglishUpdateView.as_view(),
         name="en_suggestions_dashboard_update"),
    path("en/suggestions/<int:id>/delete/", views.SuggestionsEnglishDeleteView.as_view(),
         name="en_suggestions_dashboard_delete"),

    path("ar/suggestions/", views.SuggestionsArabicListView.as_view(),
         name="ar_suggestions_dashboard_list"),
    path("ar/suggestions/create/", views.SuggestionsArabicCreateView.as_view(),
         name="ar_suggestions_dashboard_create"),
    path("ar/suggestions/<int:id>/", views.SuggestionsArabicDetailView.as_view(),
         name="ar_suggestions_dashboard_detail"),
    path("ar/suggestions/<int:id>/update/", views.SuggestionsArabicUpdateView.as_view(),
         name="ar_suggestions_dashboard_update"),
    path("ar/suggestions/<int:id>/delete/", views.SuggestionsArabicDeleteView.as_view(),
         name="ar_suggestions_dashboard_delete"),

    # =============== FAQ ===============
    path("en/faq/", views.FAQEnglishListView.as_view(),
         name="en_faq_dashboard_list"),
    path("en/faq/create/", views.FAQEnglishCreateView.as_view(),
         name="en_faq_dashboard_create"),
    path("en/faq/<int:id>/", views.FAQEnglishDetailView.as_view(),
         name="en_faq_dashboard_detail"),
    path("en/faq/<int:id>/update/", views.FAQEnglishUpdateView.as_view(),
         name="en_faq_dashboard_update"),
    path("en/faq/<int:id>/delete/", views.FAQEnglishDeleteView.as_view(),
         name="en_faq_dashboard_delete"),

    path("faq/", views.FAQArabicListView.as_view(),
         name="ar_faq_dashboard_list"),
    path("faq/create/", views.FAQArabicCreateView.as_view(),
         name="ar_faq_dashboard_create"),
    path("faq/<int:id>/", views.FAQArabicDetailView.as_view(),
         name="ar_faq_dashboard_detail"),
    path("faq/<int:id>/update/", views.FAQArabicUpdateView.as_view(),
         name="ar_faq_dashboard_update"),
    path("faq/<int:id>/delete/", views.FAQArabicDeleteView.as_view(),
         name="ar_faq_dashboard_delete"),

    # =============== News ===============
    path("en/news/", views.NewsEnglishListView.as_view(),
         name="en_news_dashboard_list"),
    path("en/news/create/", views.NewsEnglishCreateView.as_view(),
         name="en_news_dashboard_create"),
    path("en/news/<int:id>/", views.NewsEnglishDetailView.as_view(),
         name="en_news_dashboard_detail"),
    path("en/news/<int:id>/update/", views.NewsEnglishUpdateView.as_view(),
         name="en_news_dashboard_update"),
    path("en/news/<int:id>/delete/", views.NewsEnglishDeleteView.as_view(),
         name="en_news_dashboard_delete"),

    path("ar/news/", views.NewsArabicListView.as_view(),
         name="ar_news_dashboard_list"),
    path("ar/news/create/", views.NewsArabicCreateView.as_view(),
         name="ar_news_dashboard_create"),
    path("ar/news/<int:id>/", views.NewsArabicDetailView.as_view(),
         name="ar_news_dashboard_detail"),
    path("ar/news/<int:id>/update/", views.NewsArabicUpdateView.as_view(),
         name="ar_news_dashboard_update"),
    path("ar/news/<int:id>/delete/", views.NewsArabicDeleteView.as_view(),
         name="ar_news_dashboard_delete"),

    # =============== Products ===============
    path("en/products/", views.ProductEnglishListView.as_view(),
         name="en_products_dashboard_list"),
    path("en/products/create/", views.ProductEnglishCreateView.as_view(),
         name="en_products_dashboard_create"),
    path("en/products/<int:id>/", views.ProductEnglishDetailView.as_view(),
         name="en_products_dashboard_detail"),
    path("en/products/<int:id>/update/", views.ProductEnglishUpdateView.as_view(),
         name="en_products_dashboard_update"),
    path("en/products/<int:id>/delete/", views.ProductEnglishDeleteView.as_view(),
         name="en_products_dashboard_delete"),

    path("ar/products/", views.ProductArabicListView.as_view(),
         name="ar_products_dashboard_list"),
    path("ar/products/create/", views.ProductArabicCreateView.as_view(),
         name="ar_products_dashboard_create"),
    path("ar/products/<int:id>/", views.ProductArabicDetailView.as_view(),
         name="ar_products_dashboard_detail"),
    path("ar/products/<int:id>/update/", views.ProductArabicUpdateView.as_view(),
         name="ar_products_dashboard_update"),
    path("ar/products/<int:id>/delete/", views.ProductArabicDeleteView.as_view(),
         name="ar_products_dashboard_delete"),
]
