# Generated by Django 5.0.6 on 2024-10-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.BooleanField(default=True, verbose_name='Is Read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Submit')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
