# Generated by Django 5.0.6 on 2024-10-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is Read?'),
        ),
    ]
