# Generated by Django 5.1.1 on 2024-10-24 12:32

import aboutus.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to=aboutus.utils.upload_image_achievement, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Achievement Arabic',
                'verbose_name_plural': 'Achievement Arabic',
            },
        ),
        migrations.CreateModel(
            name='AchievementEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to=aboutus.utils.upload_image_achievement, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Achievement English',
                'verbose_name_plural': 'Achievement English',
            },
        ),
        migrations.CreateModel(
            name='TeamArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=aboutus.utils.upload_image_team, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Team Arabic',
                'verbose_name_plural': 'Team Arabic',
            },
        ),
        migrations.CreateModel(
            name='TeamEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=aboutus.utils.upload_image_team, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Team English',
                'verbose_name_plural': 'Team English',
            },
        ),
    ]
