# Generated by Django 5.1.1 on 2024-09-16 08:24

import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('content_en', models.TextField(verbose_name='Content EN')),
                ('content_ar', models.TextField(verbose_name='Content AR')),
                ('count_employee', models.IntegerField(verbose_name='Number of employees')),
                ('count_product', models.IntegerField(verbose_name='Number of products')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_about, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('content_en', models.TextField(verbose_name='Content EN')),
                ('content_ar', models.TextField(verbose_name='Content AR')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_choose_us, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'ChooseUs',
                'verbose_name_plural': 'ChooseUs',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_comment, verbose_name='Image')),
                ('content_en', models.TextField(verbose_name='Content EN')),
                ('content_ar', models.TextField(verbose_name='Content AR')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('status', models.BooleanField(default=True, verbose_name='Be Shown?')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('content_en', models.TextField(verbose_name='Content EN')),
                ('content_ar', models.TextField(verbose_name='Content AR')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service, verbose_name='Image')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service_icon, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Be Shown?')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('sub_title_en', models.CharField(max_length=255, verbose_name='Sub Title EN')),
                ('sub_title_ar', models.CharField(max_length=255, verbose_name='Sub Title EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_sliders, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Be Shown?')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
