# Generated by Django 5.1.1 on 2024-09-16 08:28

import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service_icon, verbose_name='Image Icon'),
        ),
    ]
