# Generated by Django 5.1.1 on 2024-09-16 09:41

import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_comments_fullname_comments_fullname_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('content_en', models.TextField(verbose_name='Content EN')),
                ('content_ar', models.TextField(verbose_name='Content AR')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_suggestions_icon, verbose_name='Image Icon')),
                ('status', models.BooleanField(default=True, verbose_name='Be Shown?')),
            ],
            options={
                'verbose_name': 'Suggestions',
                'verbose_name_plural': 'Suggestions',
            },
        ),
    ]
