# Generated by Django 5.1.1 on 2024-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question EN')),
                ('question_ar', models.CharField(max_length=255, verbose_name='Question AR')),
                ('answer_en', models.TextField(verbose_name='Answer EN')),
                ('answer_ar', models.TextField(verbose_name='Answer AR')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
