# Generated by Django 5.0.6 on 2024-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq_alter_comments_status_alter_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title AR'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title EN'),
        ),
    ]
