# Generated by Django 5.1.1 on 2024-10-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_sliders_sub_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='country_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country EN'),
        ),
        migrations.AddField(
            model_name='comments',
            name='country_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country EN'),
        ),
    ]
