# Generated by Django 5.1.1 on 2024-10-19 14:07

import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comments_country_ar_comments_country_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('count_employee', models.IntegerField(verbose_name='Number of employees')),
                ('count_product', models.IntegerField(verbose_name='Number of products')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_about, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'AboutUs Arabic',
                'verbose_name_plural': 'AboutUs Arabic',
            },
        ),
        migrations.CreateModel(
            name='AboutUsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('count_employee', models.IntegerField(verbose_name='Number of employees')),
                ('count_product', models.IntegerField(verbose_name='Number of products')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_about, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'AboutUs English',
                'verbose_name_plural': 'AboutUs English',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_choose_us, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'ChooseUs Arabic',
                'verbose_name_plural': 'ChooseUs Arabic',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_choose_us, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'ChooseUs English',
                'verbose_name_plural': 'ChooseUs English',
            },
        ),
        migrations.CreateModel(
            name='CommentsArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_comment, verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name EN')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country EN')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Comments Arabic',
                'verbose_name_plural': 'Comments Arabic',
            },
        ),
        migrations.CreateModel(
            name='CommentsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_comment, verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name EN')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country EN')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Comments English',
                'verbose_name_plural': 'Comments English',
            },
        ),
        migrations.CreateModel(
            name='FAQArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question EN')),
                ('answer', models.TextField(verbose_name='Answer EN')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'FAQ Arabic',
                'verbose_name_plural': 'FAQs Arabic',
            },
        ),
        migrations.CreateModel(
            name='FAQEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question EN')),
                ('answer', models.TextField(verbose_name='Answer EN')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'FAQ English',
                'verbose_name_plural': 'FAQs English',
            },
        ),
        migrations.CreateModel(
            name='ServiceArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service, verbose_name='Image')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service_icon, verbose_name='Image Icon')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Service Arabic',
                'verbose_name_plural': 'Service Arabic',
            },
        ),
        migrations.CreateModel(
            name='ServiceEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service, verbose_name='Image')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_service_icon, verbose_name='Image Icon')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Service English',
                'verbose_name_plural': 'Service English',
            },
        ),
        migrations.CreateModel(
            name='SlidersArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title AR')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title EN')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_sliders, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Slider Arabic',
                'verbose_name_plural': 'Sliders Arabic',
            },
        ),
        migrations.CreateModel(
            name='SlidersEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_sliders, verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Slider English',
                'verbose_name_plural': 'Sliders English',
            },
        ),
        migrations.CreateModel(
            name='SuggestionsArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_suggestions_icon, verbose_name='Image Icon')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Suggestions Arabic',
                'verbose_name_plural': 'Suggestions Arabic',
            },
        ),
        migrations.CreateModel(
            name='SuggestionsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title EN')),
                ('content', models.TextField(verbose_name='Content EN')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=home.utils.upload_image_suggestions_icon, verbose_name='Image Icon')),
                ('status', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Suggestions English',
                'verbose_name_plural': 'Suggestions English',
            },
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ChooseUs',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Sliders',
        ),
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
