# Generated by Django 5.1.1 on 2024-10-23 09:05

import regulation.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0002_alter_social_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=regulation.utils.upload_image_setting, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Setting English',
                'verbose_name_plural': 'Settings English',
            },
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsArabic',
        ),
        migrations.AlterModelOptions(
            name='settingsarabic',
            options={'verbose_name': 'Setting Arabic', 'verbose_name_plural': 'Settings Arabic'},
        ),
    ]
