# Generated by Django 5.1.1 on 2024-10-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productarbic_productenglish_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductArbic',
            new_name='ProductArabic',
        ),
    ]
