# Generated by Django 5.1.1 on 2024-10-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_productarbic_productarabic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productarabic',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='productenglish',
            name='desc',
        ),
    ]
